### ISSUE TITLE
Mkstemp failed on Mac OS X

### ISSUE THREAD

**Issue by kgorinson** [rsvp/speedtest-linux#5]
Whenever I run the script on Mac OS X, I get the following error (the part after the tmp is different each time)

`mktemp: mkstemp failed on /dev/shm/88_speedtest.sh_tmp.jVA7zHF6Uj: No such file or directory`

Also if I run 

`echo "$(curl -skLO https://git.io/speedtest.sh && chmod +x speedtest.sh && ./speedtest.sh)"`

I get a blank output and it doesn't actually download the script. I have curl and jq installed.

**Comment by rsvp** [comment]
hi @kgor93 as the title of this repo says, it's ***speedtest-linux***,
i.e. for **Linux**. There are so many annoying differences from OS X
because their base is FreeBSD. The RAM folder `/dev/shm` may be
called `/run/shm` -- so if that fails just substitute `/tmp` instead,
which is universal among *nix, in your forked repo.
We prefer to avoid writing to disk.

That magic one-liner under OS X will obviously fail in the third part
which executes `./speedtest.sh` -- normally we would handle
any error, but being a one-liner it omitted the fourth part, e.g.:
`|| echo 'Mission failed.'` 

By the way, speedtest internally does take averages to produce
its results for some measurement accuracy. So don't worry
too much, it's better to take more readings at distant time intervals.
You seem to be already using awk, so use that to take averages of the
last N readings from the log file.
